services:
  frontend:
    build: ./frontend
    container_name: minecraft-panel-frontend
    restart: unless-stopped
    ports:
      - "8081:80"
    networks:
      - minecraft-net
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: minecraft-panel-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/usr/src/app/data
      - ./servers:/usr/src/app/servers
      - ./backend/firebase-adminsdk.json:/usr/src/app/firebase-adminsdk.json
    networks:
      - minecraft-net

  laravel-api:
    build: ./proservers-billing
    container_name: minecraft-panel-laravel
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./proservers-billing:/app
    networks:
      - minecraft-net

  discord-bot:
    build: ./proservers-bot
    container_name: minecraft-discord-bot
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - ./proservers-billing/.env
    networks:
      - minecraft-net

networks:
  minecraft-net:
    name: minecraft-panel_minecraft-net
    driver: bridge
