server {
    listen 80;
    server_name professional-servers.com.ar www.professional-servers.com.ar;

    # Límite para subir modpacks gigantes
    client_max_body_size 10000M;

    # 1. FRONTEND -> Todo el tráfico base va a tu HTML puro
    location / {
        proxy_pass http://minecraft-panel-frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 2. LARAVEL API -> Solo escucha peticiones de usuarios, perfiles y pagos
    location ~ ^/api/(registro|checkout|perfil|user) {
        proxy_pass http://minecraft-panel-laravel:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 3. NODE.JS DAEMON -> Todo el control de Docker, archivos y CurseForge va a Node
    location /api/ {
        proxy_pass http://minecraft-panel-backend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 4. WEBSOCKETS -> Consola en vivo de Minecraft
    location /socket.io/ {
        proxy_pass http://minecraft-panel-backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}